# this is used for local development only
FROM python:3.13

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    git \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir dbt-postgres==1.8.0

WORKDIR /usr/app

COPY . /usr/app

CMD ["bash"]