# this is used for local development only
FROM python:3.13-alpine

RUN apk update && apk add --no-cache \
      bash \
      build-base \
      postgresql-dev \
      git

RUN pip install --no-cache-dir dbt-postgres==1.8.0

WORKDIR /usr/app

COPY . /usr/app

CMD ["bash"]